#define TEST            ("AT")
#define REQUEST         ("GET /v1/exchangerate/BTC/GBP HTTP/1.1\r\nHost: rest.coinapi.io\r\nX-CoinAPI-Key: 4354354-NOT-A-REAL-API-KEY-432254543\r\nAccept: application/json\r\n\r\n")
#define REQUEST_SIZE    ("143")
#define HOST            ("rest.coinapi.io")
#define PORT            ("80")
#define PROTOCOL        ("TCP")